/**
 * Lista de países para /check-in — el desplegable de "Place of Origin" y,
 * desde 2026-09-14, también el selector de código de país del teléfono
 * ("What number can we reach you at?"). A pedido de Iván, para que esos
 * datos no dependan de que el huésped escriba bien el nombre del país o
 * su código de área (evita mojibake/variantes que después tocaría limpiar
 * a mano, el mismo tipo de problema ya encontrado antes con "país" en
 * Marketing, ver CLAUDE.md). Los ~195 países reconocidos por la ONU más
 * un puñado de territorios que sí aparecen en huéspedes reales de este
 * proyecto (Puerto Rico, Hong Kong, Taiwán).
 */
export interface Pais {
  es: string;
  en: string;
  /** ISO 3166-1 alpha-2 — también sirve para derivar el emoji de bandera. */
  iso: string;
  /** Código de llamada E.164, con el "+". */
  telefono: string;
}

export const PAISES: Pais[] = [
  { es: "Afganistán", en: "Afghanistan", iso: "AF", telefono: "+93" },
  { es: "Albania", en: "Albania", iso: "AL", telefono: "+355" },
  { es: "Alemania", en: "Germany", iso: "DE", telefono: "+49" },
  { es: "Andorra", en: "Andorra", iso: "AD", telefono: "+376" },
  { es: "Angola", en: "Angola", iso: "AO", telefono: "+244" },
  { es: "Antigua y Barbuda", en: "Antigua and Barbuda", iso: "AG", telefono: "+1268" },
  { es: "Arabia Saudita", en: "Saudi Arabia", iso: "SA", telefono: "+966" },
  { es: "Argelia", en: "Algeria", iso: "DZ", telefono: "+213" },
  { es: "Argentina", en: "Argentina", iso: "AR", telefono: "+54" },
  { es: "Armenia", en: "Armenia", iso: "AM", telefono: "+374" },
  { es: "Australia", en: "Australia", iso: "AU", telefono: "+61" },
  { es: "Austria", en: "Austria", iso: "AT", telefono: "+43" },
  { es: "Azerbaiyán", en: "Azerbaijan", iso: "AZ", telefono: "+994" },
  { es: "Bahamas", en: "Bahamas", iso: "BS", telefono: "+1242" },
  { es: "Bangladés", en: "Bangladesh", iso: "BD", telefono: "+880" },
  { es: "Barbados", en: "Barbados", iso: "BB", telefono: "+1246" },
  { es: "Baréin", en: "Bahrain", iso: "BH", telefono: "+973" },
  { es: "Bélgica", en: "Belgium", iso: "BE", telefono: "+32" },
  { es: "Belice", en: "Belize", iso: "BZ", telefono: "+501" },
  { es: "Benín", en: "Benin", iso: "BJ", telefono: "+229" },
  { es: "Bielorrusia", en: "Belarus", iso: "BY", telefono: "+375" },
  { es: "Birmania (Myanmar)", en: "Myanmar (Burma)", iso: "MM", telefono: "+95" },
  { es: "Bolivia", en: "Bolivia", iso: "BO", telefono: "+591" },
  { es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina", iso: "BA", telefono: "+387" },
  { es: "Botsuana", en: "Botswana", iso: "BW", telefono: "+267" },
  { es: "Brasil", en: "Brazil", iso: "BR", telefono: "+55" },
  { es: "Brunéi", en: "Brunei", iso: "BN", telefono: "+673" },
  { es: "Bulgaria", en: "Bulgaria", iso: "BG", telefono: "+359" },
  { es: "Burkina Faso", en: "Burkina Faso", iso: "BF", telefono: "+226" },
  { es: "Burundi", en: "Burundi", iso: "BI", telefono: "+257" },
  { es: "Bután", en: "Bhutan", iso: "BT", telefono: "+975" },
  { es: "Cabo Verde", en: "Cape Verde", iso: "CV", telefono: "+238" },
  { es: "Camboya", en: "Cambodia", iso: "KH", telefono: "+855" },
  { es: "Camerún", en: "Cameroon", iso: "CM", telefono: "+237" },
  { es: "Canadá", en: "Canada", iso: "CA", telefono: "+1" },
  { es: "Catar", en: "Qatar", iso: "QA", telefono: "+974" },
  { es: "Chad", en: "Chad", iso: "TD", telefono: "+235" },
  { es: "Chile", en: "Chile", iso: "CL", telefono: "+56" },
  { es: "China", en: "China", iso: "CN", telefono: "+86" },
  { es: "Chipre", en: "Cyprus", iso: "CY", telefono: "+357" },
  { es: "Ciudad del Vaticano", en: "Vatican City", iso: "VA", telefono: "+379" },
  { es: "Colombia", en: "Colombia", iso: "CO", telefono: "+57" },
  { es: "Comoras", en: "Comoros", iso: "KM", telefono: "+269" },
  { es: "Corea del Norte", en: "North Korea", iso: "KP", telefono: "+850" },
  { es: "Corea del Sur", en: "South Korea", iso: "KR", telefono: "+82" },
  { es: "Costa de Marfil", en: "Ivory Coast", iso: "CI", telefono: "+225" },
  { es: "Costa Rica", en: "Costa Rica", iso: "CR", telefono: "+506" },
  { es: "Croacia", en: "Croatia", iso: "HR", telefono: "+385" },
  { es: "Cuba", en: "Cuba", iso: "CU", telefono: "+53" },
  { es: "Dinamarca", en: "Denmark", iso: "DK", telefono: "+45" },
  { es: "Dominica", en: "Dominica", iso: "DM", telefono: "+1767" },
  { es: "Ecuador", en: "Ecuador", iso: "EC", telefono: "+593" },
  { es: "Egipto", en: "Egypt", iso: "EG", telefono: "+20" },
  { es: "El Salvador", en: "El Salvador", iso: "SV", telefono: "+503" },
  { es: "Emiratos Árabes Unidos", en: "United Arab Emirates", iso: "AE", telefono: "+971" },
  { es: "Eritrea", en: "Eritrea", iso: "ER", telefono: "+291" },
  { es: "Eslovaquia", en: "Slovakia", iso: "SK", telefono: "+421" },
  { es: "Eslovenia", en: "Slovenia", iso: "SI", telefono: "+386" },
  { es: "España", en: "Spain", iso: "ES", telefono: "+34" },
  { es: "Estados Unidos", en: "United States", iso: "US", telefono: "+1" },
  { es: "Estonia", en: "Estonia", iso: "EE", telefono: "+372" },
  { es: "Esuatini", en: "Eswatini", iso: "SZ", telefono: "+268" },
  { es: "Etiopía", en: "Ethiopia", iso: "ET", telefono: "+251" },
  { es: "Filipinas", en: "Philippines", iso: "PH", telefono: "+63" },
  { es: "Finlandia", en: "Finland", iso: "FI", telefono: "+358" },
  { es: "Fiyi", en: "Fiji", iso: "FJ", telefono: "+679" },
  { es: "Francia", en: "France", iso: "FR", telefono: "+33" },
  { es: "Gabón", en: "Gabon", iso: "GA", telefono: "+241" },
  { es: "Gambia", en: "Gambia", iso: "GM", telefono: "+220" },
  { es: "Georgia", en: "Georgia", iso: "GE", telefono: "+995" },
  { es: "Ghana", en: "Ghana", iso: "GH", telefono: "+233" },
  { es: "Granada", en: "Grenada", iso: "GD", telefono: "+1473" },
  { es: "Grecia", en: "Greece", iso: "GR", telefono: "+30" },
  { es: "Guatemala", en: "Guatemala", iso: "GT", telefono: "+502" },
  { es: "Guyana", en: "Guyana", iso: "GY", telefono: "+592" },
  { es: "Guinea", en: "Guinea", iso: "GN", telefono: "+224" },
  { es: "Guinea-Bisáu", en: "Guinea-Bissau", iso: "GW", telefono: "+245" },
  { es: "Guinea Ecuatorial", en: "Equatorial Guinea", iso: "GQ", telefono: "+240" },
  { es: "Haití", en: "Haiti", iso: "HT", telefono: "+509" },
  { es: "Honduras", en: "Honduras", iso: "HN", telefono: "+504" },
  { es: "Hong Kong", en: "Hong Kong", iso: "HK", telefono: "+852" },
  { es: "Hungría", en: "Hungary", iso: "HU", telefono: "+36" },
  { es: "India", en: "India", iso: "IN", telefono: "+91" },
  { es: "Indonesia", en: "Indonesia", iso: "ID", telefono: "+62" },
  { es: "Irak", en: "Iraq", iso: "IQ", telefono: "+964" },
  { es: "Irán", en: "Iran", iso: "IR", telefono: "+98" },
  { es: "Irlanda", en: "Ireland", iso: "IE", telefono: "+353" },
  { es: "Islandia", en: "Iceland", iso: "IS", telefono: "+354" },
  { es: "Islas Marshall", en: "Marshall Islands", iso: "MH", telefono: "+692" },
  { es: "Islas Salomón", en: "Solomon Islands", iso: "SB", telefono: "+677" },
  { es: "Israel", en: "Israel", iso: "IL", telefono: "+972" },
  { es: "Italia", en: "Italy", iso: "IT", telefono: "+39" },
  { es: "Jamaica", en: "Jamaica", iso: "JM", telefono: "+1876" },
  { es: "Japón", en: "Japan", iso: "JP", telefono: "+81" },
  { es: "Jordania", en: "Jordan", iso: "JO", telefono: "+962" },
  { es: "Kazajistán", en: "Kazakhstan", iso: "KZ", telefono: "+7" },
  { es: "Kenia", en: "Kenya", iso: "KE", telefono: "+254" },
  { es: "Kirguistán", en: "Kyrgyzstan", iso: "KG", telefono: "+996" },
  { es: "Kiribati", en: "Kiribati", iso: "KI", telefono: "+686" },
  { es: "Kuwait", en: "Kuwait", iso: "KW", telefono: "+965" },
  { es: "Laos", en: "Laos", iso: "LA", telefono: "+856" },
  { es: "Lesoto", en: "Lesotho", iso: "LS", telefono: "+266" },
  { es: "Letonia", en: "Latvia", iso: "LV", telefono: "+371" },
  { es: "Líbano", en: "Lebanon", iso: "LB", telefono: "+961" },
  { es: "Liberia", en: "Liberia", iso: "LR", telefono: "+231" },
  { es: "Libia", en: "Libya", iso: "LY", telefono: "+218" },
  { es: "Liechtenstein", en: "Liechtenstein", iso: "LI", telefono: "+423" },
  { es: "Lituania", en: "Lithuania", iso: "LT", telefono: "+370" },
  { es: "Luxemburgo", en: "Luxembourg", iso: "LU", telefono: "+352" },
  { es: "Macedonia del Norte", en: "North Macedonia", iso: "MK", telefono: "+389" },
  { es: "Madagascar", en: "Madagascar", iso: "MG", telefono: "+261" },
  { es: "Malasia", en: "Malaysia", iso: "MY", telefono: "+60" },
  { es: "Malaui", en: "Malawi", iso: "MW", telefono: "+265" },
  { es: "Maldivas", en: "Maldives", iso: "MV", telefono: "+960" },
  { es: "Malí", en: "Mali", iso: "ML", telefono: "+223" },
  { es: "Malta", en: "Malta", iso: "MT", telefono: "+356" },
  { es: "Marruecos", en: "Morocco", iso: "MA", telefono: "+212" },
  { es: "Mauricio", en: "Mauritius", iso: "MU", telefono: "+230" },
  { es: "Mauritania", en: "Mauritania", iso: "MR", telefono: "+222" },
  { es: "México", en: "Mexico", iso: "MX", telefono: "+52" },
  { es: "Micronesia", en: "Micronesia", iso: "FM", telefono: "+691" },
  { es: "Moldavia", en: "Moldova", iso: "MD", telefono: "+373" },
  { es: "Mónaco", en: "Monaco", iso: "MC", telefono: "+377" },
  { es: "Mongolia", en: "Mongolia", iso: "MN", telefono: "+976" },
  { es: "Montenegro", en: "Montenegro", iso: "ME", telefono: "+382" },
  { es: "Mozambique", en: "Mozambique", iso: "MZ", telefono: "+258" },
  { es: "Namibia", en: "Namibia", iso: "NA", telefono: "+264" },
  { es: "Nauru", en: "Nauru", iso: "NR", telefono: "+674" },
  { es: "Nepal", en: "Nepal", iso: "NP", telefono: "+977" },
  { es: "Nicaragua", en: "Nicaragua", iso: "NI", telefono: "+505" },
  { es: "Níger", en: "Niger", iso: "NE", telefono: "+227" },
  { es: "Nigeria", en: "Nigeria", iso: "NG", telefono: "+234" },
  { es: "Noruega", en: "Norway", iso: "NO", telefono: "+47" },
  { es: "Nueva Zelanda", en: "New Zealand", iso: "NZ", telefono: "+64" },
  { es: "Omán", en: "Oman", iso: "OM", telefono: "+968" },
  { es: "Países Bajos", en: "Netherlands", iso: "NL", telefono: "+31" },
  { es: "Pakistán", en: "Pakistan", iso: "PK", telefono: "+92" },
  { es: "Palaos", en: "Palau", iso: "PW", telefono: "+680" },
  { es: "Panamá", en: "Panama", iso: "PA", telefono: "+507" },
  { es: "Papúa Nueva Guinea", en: "Papua New Guinea", iso: "PG", telefono: "+675" },
  { es: "Paraguay", en: "Paraguay", iso: "PY", telefono: "+595" },
  { es: "Perú", en: "Peru", iso: "PE", telefono: "+51" },
  { es: "Polonia", en: "Poland", iso: "PL", telefono: "+48" },
  { es: "Portugal", en: "Portugal", iso: "PT", telefono: "+351" },
  { es: "Puerto Rico", en: "Puerto Rico", iso: "PR", telefono: "+1" },
  { es: "Reino Unido", en: "United Kingdom", iso: "GB", telefono: "+44" },
  { es: "República Centroafricana", en: "Central African Republic", iso: "CF", telefono: "+236" },
  { es: "República Checa", en: "Czech Republic", iso: "CZ", telefono: "+420" },
  { es: "República del Congo", en: "Republic of the Congo", iso: "CG", telefono: "+242" },
  { es: "República Democrática del Congo", en: "Democratic Republic of the Congo", iso: "CD", telefono: "+243" },
  { es: "República Dominicana", en: "Dominican Republic", iso: "DO", telefono: "+1" },
  { es: "Ruanda", en: "Rwanda", iso: "RW", telefono: "+250" },
  { es: "Rumanía", en: "Romania", iso: "RO", telefono: "+40" },
  { es: "Rusia", en: "Russia", iso: "RU", telefono: "+7" },
  { es: "Samoa", en: "Samoa", iso: "WS", telefono: "+685" },
  { es: "San Cristóbal y Nieves", en: "Saint Kitts and Nevis", iso: "KN", telefono: "+1869" },
  { es: "San Marino", en: "San Marino", iso: "SM", telefono: "+378" },
  { es: "San Vicente y las Granadinas", en: "Saint Vincent and the Grenadines", iso: "VC", telefono: "+1784" },
  { es: "Santa Lucía", en: "Saint Lucia", iso: "LC", telefono: "+1758" },
  { es: "Santo Tomé y Príncipe", en: "São Tomé and Príncipe", iso: "ST", telefono: "+239" },
  { es: "Senegal", en: "Senegal", iso: "SN", telefono: "+221" },
  { es: "Serbia", en: "Serbia", iso: "RS", telefono: "+381" },
  { es: "Seychelles", en: "Seychelles", iso: "SC", telefono: "+248" },
  { es: "Sierra Leona", en: "Sierra Leone", iso: "SL", telefono: "+232" },
  { es: "Singapur", en: "Singapore", iso: "SG", telefono: "+65" },
  { es: "Siria", en: "Syria", iso: "SY", telefono: "+963" },
  { es: "Somalia", en: "Somalia", iso: "SO", telefono: "+252" },
  { es: "Sri Lanka", en: "Sri Lanka", iso: "LK", telefono: "+94" },
  { es: "Suazilandia", en: "Swaziland", iso: "SZ", telefono: "+268" },
  { es: "Sudáfrica", en: "South Africa", iso: "ZA", telefono: "+27" },
  { es: "Sudán", en: "Sudan", iso: "SD", telefono: "+249" },
  { es: "Sudán del Sur", en: "South Sudan", iso: "SS", telefono: "+211" },
  { es: "Suecia", en: "Sweden", iso: "SE", telefono: "+46" },
  { es: "Suiza", en: "Switzerland", iso: "CH", telefono: "+41" },
  { es: "Surinam", en: "Suriname", iso: "SR", telefono: "+597" },
  { es: "Tailandia", en: "Thailand", iso: "TH", telefono: "+66" },
  { es: "Taiwán", en: "Taiwan", iso: "TW", telefono: "+886" },
  { es: "Tanzania", en: "Tanzania", iso: "TZ", telefono: "+255" },
  { es: "Tayikistán", en: "Tajikistan", iso: "TJ", telefono: "+992" },
  { es: "Timor Oriental", en: "East Timor", iso: "TL", telefono: "+670" },
  { es: "Togo", en: "Togo", iso: "TG", telefono: "+228" },
  { es: "Tonga", en: "Tonga", iso: "TO", telefono: "+676" },
  { es: "Trinidad y Tobago", en: "Trinidad and Tobago", iso: "TT", telefono: "+1868" },
  { es: "Túnez", en: "Tunisia", iso: "TN", telefono: "+216" },
  { es: "Turkmenistán", en: "Turkmenistan", iso: "TM", telefono: "+993" },
  { es: "Turquía", en: "Turkey", iso: "TR", telefono: "+90" },
  { es: "Tuvalu", en: "Tuvalu", iso: "TV", telefono: "+688" },
  { es: "Ucrania", en: "Ukraine", iso: "UA", telefono: "+380" },
  { es: "Uganda", en: "Uganda", iso: "UG", telefono: "+256" },
  { es: "Uruguay", en: "Uruguay", iso: "UY", telefono: "+598" },
  { es: "Uzbekistán", en: "Uzbekistan", iso: "UZ", telefono: "+998" },
  { es: "Vanuatu", en: "Vanuatu", iso: "VU", telefono: "+678" },
  { es: "Venezuela", en: "Venezuela", iso: "VE", telefono: "+58" },
  { es: "Vietnam", en: "Vietnam", iso: "VN", telefono: "+84" },
  { es: "Yemen", en: "Yemen", iso: "YE", telefono: "+967" },
  { es: "Yibuti", en: "Djibouti", iso: "DJ", telefono: "+253" },
  { es: "Zambia", en: "Zambia", iso: "ZM", telefono: "+260" },
  { es: "Zimbabue", en: "Zimbabwe", iso: "ZW", telefono: "+263" },
];

export function paisesOrdenados(lang: "es" | "en"): Pais[] {
  return [...PAISES].sort((a, b) => a[lang].localeCompare(b[lang], lang));
}

/** Emoji de bandera a partir del ISO 3166-1 alpha-2 (letras → Regional Indicator Symbols). */
export function bandera(iso: string): string {
  return [...iso.toUpperCase()].map((c) => String.fromCodePoint(c.charCodeAt(0) + 127397)).join("");
}

/**
 * Países para el selector de código telefónico, ordenados por código de
 * llamada (agrupa +1 EE. UU./Canadá/Caribe junto, que es como la gente
 * suele buscar un código de país en un teléfono) y sin duplicar +1/+7
 * entre sí — a diferencia de `paisesOrdenados`, que ordena por nombre.
 */
export function paisesTelefono(lang: "es" | "en"): Pais[] {
  return [...PAISES].sort((a, b) => {
    const porCodigo = a.telefono.localeCompare(b.telefono, "en", { numeric: true });
    return porCodigo !== 0 ? porCodigo : a[lang].localeCompare(b[lang], lang);
  });
}
