/**
 * Lista de países para el desplegable de "Place of Origin" en /check-in —
 * a pedido de Iván, para que ese dato no dependa de que el huésped
 * escriba bien el nombre del país (evita mojibake/variantes que después
 * tocaría limpiar a mano, el mismo tipo de problema ya encontrado antes
 * con "país" en Marketing, ver CLAUDE.md). Los ~195 países reconocidos
 * por la ONU más un puñado de territorios que sí aparecen en huéspedes
 * reales de este proyecto (Puerto Rico, Hong Kong, Taiwán).
 */
export interface Pais {
  es: string;
  en: string;
}

export const PAISES: Pais[] = [
  { es: "Afganistán", en: "Afghanistan" },
  { es: "Albania", en: "Albania" },
  { es: "Alemania", en: "Germany" },
  { es: "Andorra", en: "Andorra" },
  { es: "Angola", en: "Angola" },
  { es: "Antigua y Barbuda", en: "Antigua and Barbuda" },
  { es: "Arabia Saudita", en: "Saudi Arabia" },
  { es: "Argelia", en: "Algeria" },
  { es: "Argentina", en: "Argentina" },
  { es: "Armenia", en: "Armenia" },
  { es: "Australia", en: "Australia" },
  { es: "Austria", en: "Austria" },
  { es: "Azerbaiyán", en: "Azerbaijan" },
  { es: "Bahamas", en: "Bahamas" },
  { es: "Bangladés", en: "Bangladesh" },
  { es: "Barbados", en: "Barbados" },
  { es: "Baréin", en: "Bahrain" },
  { es: "Bélgica", en: "Belgium" },
  { es: "Belice", en: "Belize" },
  { es: "Benín", en: "Benin" },
  { es: "Bielorrusia", en: "Belarus" },
  { es: "Birmania (Myanmar)", en: "Myanmar (Burma)" },
  { es: "Bolivia", en: "Bolivia" },
  { es: "Bosnia y Herzegovina", en: "Bosnia and Herzegovina" },
  { es: "Botsuana", en: "Botswana" },
  { es: "Brasil", en: "Brazil" },
  { es: "Brunéi", en: "Brunei" },
  { es: "Bulgaria", en: "Bulgaria" },
  { es: "Burkina Faso", en: "Burkina Faso" },
  { es: "Burundi", en: "Burundi" },
  { es: "Bután", en: "Bhutan" },
  { es: "Cabo Verde", en: "Cape Verde" },
  { es: "Camboya", en: "Cambodia" },
  { es: "Camerún", en: "Cameroon" },
  { es: "Canadá", en: "Canada" },
  { es: "Catar", en: "Qatar" },
  { es: "Chad", en: "Chad" },
  { es: "Chile", en: "Chile" },
  { es: "China", en: "China" },
  { es: "Chipre", en: "Cyprus" },
  { es: "Ciudad del Vaticano", en: "Vatican City" },
  { es: "Colombia", en: "Colombia" },
  { es: "Comoras", en: "Comoros" },
  { es: "Corea del Norte", en: "North Korea" },
  { es: "Corea del Sur", en: "South Korea" },
  { es: "Costa de Marfil", en: "Ivory Coast" },
  { es: "Costa Rica", en: "Costa Rica" },
  { es: "Croacia", en: "Croatia" },
  { es: "Cuba", en: "Cuba" },
  { es: "Dinamarca", en: "Denmark" },
  { es: "Dominica", en: "Dominica" },
  { es: "Ecuador", en: "Ecuador" },
  { es: "Egipto", en: "Egypt" },
  { es: "El Salvador", en: "El Salvador" },
  { es: "Emiratos Árabes Unidos", en: "United Arab Emirates" },
  { es: "Eritrea", en: "Eritrea" },
  { es: "Eslovaquia", en: "Slovakia" },
  { es: "Eslovenia", en: "Slovenia" },
  { es: "España", en: "Spain" },
  { es: "Estados Unidos", en: "United States" },
  { es: "Estonia", en: "Estonia" },
  { es: "Esuatini", en: "Eswatini" },
  { es: "Etiopía", en: "Ethiopia" },
  { es: "Filipinas", en: "Philippines" },
  { es: "Finlandia", en: "Finland" },
  { es: "Fiyi", en: "Fiji" },
  { es: "Francia", en: "France" },
  { es: "Gabón", en: "Gabon" },
  { es: "Gambia", en: "Gambia" },
  { es: "Georgia", en: "Georgia" },
  { es: "Ghana", en: "Ghana" },
  { es: "Granada", en: "Grenada" },
  { es: "Grecia", en: "Greece" },
  { es: "Guatemala", en: "Guatemala" },
  { es: "Guyana", en: "Guyana" },
  { es: "Guinea", en: "Guinea" },
  { es: "Guinea-Bisáu", en: "Guinea-Bissau" },
  { es: "Guinea Ecuatorial", en: "Equatorial Guinea" },
  { es: "Haití", en: "Haiti" },
  { es: "Honduras", en: "Honduras" },
  { es: "Hong Kong", en: "Hong Kong" },
  { es: "Hungría", en: "Hungary" },
  { es: "India", en: "India" },
  { es: "Indonesia", en: "Indonesia" },
  { es: "Irak", en: "Iraq" },
  { es: "Irán", en: "Iran" },
  { es: "Irlanda", en: "Ireland" },
  { es: "Islandia", en: "Iceland" },
  { es: "Islas Marshall", en: "Marshall Islands" },
  { es: "Islas Salomón", en: "Solomon Islands" },
  { es: "Israel", en: "Israel" },
  { es: "Italia", en: "Italy" },
  { es: "Jamaica", en: "Jamaica" },
  { es: "Japón", en: "Japan" },
  { es: "Jordania", en: "Jordan" },
  { es: "Kazajistán", en: "Kazakhstan" },
  { es: "Kenia", en: "Kenya" },
  { es: "Kirguistán", en: "Kyrgyzstan" },
  { es: "Kiribati", en: "Kiribati" },
  { es: "Kuwait", en: "Kuwait" },
  { es: "Laos", en: "Laos" },
  { es: "Lesoto", en: "Lesotho" },
  { es: "Letonia", en: "Latvia" },
  { es: "Líbano", en: "Lebanon" },
  { es: "Liberia", en: "Liberia" },
  { es: "Libia", en: "Libya" },
  { es: "Liechtenstein", en: "Liechtenstein" },
  { es: "Lituania", en: "Lithuania" },
  { es: "Luxemburgo", en: "Luxembourg" },
  { es: "Macedonia del Norte", en: "North Macedonia" },
  { es: "Madagascar", en: "Madagascar" },
  { es: "Malasia", en: "Malaysia" },
  { es: "Malaui", en: "Malawi" },
  { es: "Maldivas", en: "Maldives" },
  { es: "Malí", en: "Mali" },
  { es: "Malta", en: "Malta" },
  { es: "Marruecos", en: "Morocco" },
  { es: "Mauricio", en: "Mauritius" },
  { es: "Mauritania", en: "Mauritania" },
  { es: "México", en: "Mexico" },
  { es: "Micronesia", en: "Micronesia" },
  { es: "Moldavia", en: "Moldova" },
  { es: "Mónaco", en: "Monaco" },
  { es: "Mongolia", en: "Mongolia" },
  { es: "Montenegro", en: "Montenegro" },
  { es: "Mozambique", en: "Mozambique" },
  { es: "Namibia", en: "Namibia" },
  { es: "Nauru", en: "Nauru" },
  { es: "Nepal", en: "Nepal" },
  { es: "Nicaragua", en: "Nicaragua" },
  { es: "Níger", en: "Niger" },
  { es: "Nigeria", en: "Nigeria" },
  { es: "Noruega", en: "Norway" },
  { es: "Nueva Zelanda", en: "New Zealand" },
  { es: "Omán", en: "Oman" },
  { es: "Países Bajos", en: "Netherlands" },
  { es: "Pakistán", en: "Pakistan" },
  { es: "Palaos", en: "Palau" },
  { es: "Panamá", en: "Panama" },
  { es: "Papúa Nueva Guinea", en: "Papua New Guinea" },
  { es: "Paraguay", en: "Paraguay" },
  { es: "Perú", en: "Peru" },
  { es: "Polonia", en: "Poland" },
  { es: "Portugal", en: "Portugal" },
  { es: "Puerto Rico", en: "Puerto Rico" },
  { es: "Reino Unido", en: "United Kingdom" },
  { es: "República Centroafricana", en: "Central African Republic" },
  { es: "República Checa", en: "Czech Republic" },
  { es: "República del Congo", en: "Republic of the Congo" },
  { es: "República Democrática del Congo", en: "Democratic Republic of the Congo" },
  { es: "República Dominicana", en: "Dominican Republic" },
  { es: "Ruanda", en: "Rwanda" },
  { es: "Rumanía", en: "Romania" },
  { es: "Rusia", en: "Russia" },
  { es: "Samoa", en: "Samoa" },
  { es: "San Cristóbal y Nieves", en: "Saint Kitts and Nevis" },
  { es: "San Marino", en: "San Marino" },
  { es: "San Vicente y las Granadinas", en: "Saint Vincent and the Grenadines" },
  { es: "Santa Lucía", en: "Saint Lucia" },
  { es: "Santo Tomé y Príncipe", en: "São Tomé and Príncipe" },
  { es: "Senegal", en: "Senegal" },
  { es: "Serbia", en: "Serbia" },
  { es: "Seychelles", en: "Seychelles" },
  { es: "Sierra Leona", en: "Sierra Leone" },
  { es: "Singapur", en: "Singapore" },
  { es: "Siria", en: "Syria" },
  { es: "Somalia", en: "Somalia" },
  { es: "Sri Lanka", en: "Sri Lanka" },
  { es: "Suazilandia", en: "Swaziland" },
  { es: "Sudáfrica", en: "South Africa" },
  { es: "Sudán", en: "Sudan" },
  { es: "Sudán del Sur", en: "South Sudan" },
  { es: "Suecia", en: "Sweden" },
  { es: "Suiza", en: "Switzerland" },
  { es: "Surinam", en: "Suriname" },
  { es: "Tailandia", en: "Thailand" },
  { es: "Taiwán", en: "Taiwan" },
  { es: "Tanzania", en: "Tanzania" },
  { es: "Tayikistán", en: "Tajikistan" },
  { es: "Timor Oriental", en: "East Timor" },
  { es: "Togo", en: "Togo" },
  { es: "Tonga", en: "Tonga" },
  { es: "Trinidad y Tobago", en: "Trinidad and Tobago" },
  { es: "Túnez", en: "Tunisia" },
  { es: "Turkmenistán", en: "Turkmenistan" },
  { es: "Turquía", en: "Turkey" },
  { es: "Tuvalu", en: "Tuvalu" },
  { es: "Ucrania", en: "Ukraine" },
  { es: "Uganda", en: "Uganda" },
  { es: "Uruguay", en: "Uruguay" },
  { es: "Uzbekistán", en: "Uzbekistan" },
  { es: "Vanuatu", en: "Vanuatu" },
  { es: "Venezuela", en: "Venezuela" },
  { es: "Vietnam", en: "Vietnam" },
  { es: "Yemen", en: "Yemen" },
  { es: "Yibuti", en: "Djibouti" },
  { es: "Zambia", en: "Zambia" },
  { es: "Zimbabue", en: "Zimbabwe" },
];

export function paisesOrdenados(lang: "es" | "en"): Pais[] {
  return [...PAISES].sort((a, b) => a[lang].localeCompare(b[lang], lang));
}
